### ISSUE TITLE
k8s metrics Request

### ISSUE THREAD

**Issue by ddy4633** [zhangguanzhang/Kubernetes-ansible#12]
- 版本：v1.16.9
- 问题描述：重启了下集群然后metrics就GG了检查了metrics日志没有报错，检查了下kubelet少量不相关的报错，以下yaml是扒拉下你预装的metris的yaml文件，请查看下是否有问题
- 问题截图
![](https://ftp.bmp.ovh/imgs/2020/06/3aec4a20ffd49845.png)
![](https://ftp.bmp.ovh/imgs/2020/06/014dc8d065f24bc3.png)
- 解决：尝试过删除重建不起作用，特来找馆长咨询
- 额外话题：kubectl get cs 都是unknow这个是Bug吗？describe看状态倒是正常的

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: metrics-server
      name: metrics-server
    spec:
      containers:
      - args:
        - --kubelet-preferred-address-types=InternalIP
        - --kubelet-insecure-tls
        image: zhangguanzhang/metrics-server:v0.3.6
        imagePullPolicy: IfNotPresent
        name: metrics-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /etc/localtime
          name: host-time
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metrics-server
      serviceAccountName: metrics-server
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
      - emptyDir: {}
        name: tmp-dir
```
