### ISSUE TITLE
flanneld 无法启动

### ISSUE THREAD

**Issue by frankinbj** [zhangguanzhang/Kubernetes-ansible#4]
按照你的guide， 试了几次都是到flannel 失败。 

TASK [KubernetesCoreAddons : 开机并启动flanneld] *********************************************************************
fatal: [192.168.1.17]: FAILED! => {"changed": false, "msg": "Unable to restart service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.1.18]: FAILED! => {"changed": false, "msg": "Unable to restart service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.1.38]: FAILED! => {"changed": false, "msg": "Unable to restart service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.1.28]: FAILED! => {"changed": false, "msg": "Unable to restart service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.1.27]: FAILED! => {"changed": false, "msg": "Unable to restart service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}

[root@vm17 CoreAddons]# journalctl -xe |grep flanneld
Jul 08 16:36:05 vm17.suibian.int flanneld[32209]: E0708 16:36:05.632948   32209 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Unauthorized

ifconfig
[root@vm17 CoreAddons]# ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:8d:03:72:29  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.17  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 52:54:00:4c:eb:28  txqueuelen 1000  (Ethernet)
        RX packets 4056110  bytes 543595368 (518.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3506639  bytes 782355415 (746.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 809083  bytes 110526361 (105.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 809083  bytes 110526361 (105.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by zhangguanzhang** [comment]
加我微信我远程teamview 13看看

**Comment by frankinbj** [comment]
明天的哈

发自我的华为手机


-------- 原始邮件 --------
主题：Re: [zhangguanzhang/Kubernetes-ansible] flanneld 无法启动 (#4)
发件人：zhangguanzhang
收件人：zhangguanzhang/Kubernetes-ansible
抄送：YHF ,Author


加我微信我远程teamview 13看看

―

**Comment by zhangguanzhang** [comment]
周二到周四我出差参加培训

**Comment by frankinbj** [comment]
多谢，我这两天也有事，周五再约
提前感谢！

发自我的华为手机


-------- 原始邮件 --------
主题：Re: [zhangguanzhang/Kubernetes-ansible] flanneld 无法启动 (#4)
发件人：zhangguanzhang
收件人：zhangguanzhang/Kubernetes-ansible
抄送：YHF ,Author


周二到周四我出差参加培训

―

**Comment by kevinzu007** [comment]
vim  group_vars/all.yml
version: '18.06'
改成version: '18.09' 后出现以下错误：
---------------------------------------
fatal: [192.168.11.172]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce-3:18.09.7-3.el7' found available, installed or updated", "rc": 126, "results": ["No package match
ing 'docker-ce-3:18.09.7-3.el7' found available, installed or updated"]}

**Comment by kevinzu007** [comment]
遇到同样的问题：
---------------------------------
TASK [KubernetesCoreAddons : 开机并启动flanneld] ***************************************************************************************************************************************************
fatal: [192.168.11.172]: FAILED! => {"changed": false, "msg": "Unable to start service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.11.173]: FAILED! => {"changed": false, "msg": "Unable to start service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.11.171]: FAILED! => {"changed": false, "msg": "Unable to start service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.11.174]: FAILED! => {"changed": false, "msg": "Unable to start service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.11.175]: FAILED! => {"changed": false, "msg": "Unable to start service flanneld: Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.11.171             : ok=16   changed=9    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
192.168.11.172             : ok=14   changed=11   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
192.168.11.173             : ok=14   changed=11   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
192.168.11.174             : ok=13   changed=11   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
192.168.11.175             : ok=13   changed=11   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

----------------------
[root@k8s-m1 Kubernetes-ansible]# systemctl status flanneld.service -l
● flanneld.service - Network fabric for containers
   Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled; vendor preset: disabled)
   Active: activating (start) since Thu 2019-07-11 15:38:49 CST; 14s ago
     Docs: https://github.com/coreos/flannel
 Main PID: 16325 (flanneld)
    Tasks: 11
   Memory: 6.9M
   CGroup: /system.slice/flanneld.service
           └─16325 /usr/local/bin/flanneld --kube-subnet-mgr=true --kubeconfig-file=/etc/kubernetes/flanneld.kubeconfig --ip-masq=true --iface=eth0 --public-ip 192.168.11.171 --healthz-ip 192.168.11.171 --healthz-port 8471 --v=2

Jul 11 15:38:53 k8s-m1 flanneld[16325]: E0711 15:38:53.388530   16325 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Jul 11 15:38:54 k8s-m1 flanneld[16325]: E0711 15:38:54.390377   16325 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
--------------------------

**Comment by zhangguanzhang** [comment]
提示了匿名用户，systemctl cat flanneld复制启动参数

**Comment by zhangguanzhang** [comment]
先看flanneld的kubeconfig内容正常不，
```
NODE_NAME=xxx
/usr/local/bin/flanneld -xxxxxxx
```
上面这样启动看信息

**Comment by kevinzu007** [comment]
环境（5台）：
```
[master]
192.168.11.171  hostname=k8s-m1 nodename=k8s-m1
192.168.11.172  hostname=k8s-m2 nodename=k8s-m2
192.168.11.173  hostname=k8s-m3 nodename=k8s-m3
[node]
192.168.11.174  hostname=k8s-n1 nodename=k8s-n1
192.168.11.175  hostname=k8s-n2 nodename=k8s-n2
略
```
========
```
[root@k8s-m1 ~]# systemctl cat flanneld
# /usr/lib/systemd/system/flanneld.service
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
Restart=always
RestartSec=5
# This is needed because of this: https://github.com/coreos/flannel/issues/792
# Kubernetes knows the nodes by their FQDN so we have to use the FQDN
#Environment=NODE_NAME=my-node.foo.bar.com
# Note that we don't specify any etcd option. This is because we want to talk
# to the apiserver instead. The apiserver then talks to etcd on flannel's
# behalf.
Environment=NODE_NAME=k8s-m1
ExecStart=/usr/local/bin/flanneld \
  --kube-subnet-mgr=true \
  --kubeconfig-file=/etc/kubernetes/flanneld.kubeconfig \
  --ip-masq=true \
  --iface=eth0 \
  --public-ip 192.168.11.171 \
  --healthz-ip 192.168.11.171 \
  --healthz-port 8471 \
  --v=2

[Install]
WantedBy=multi-user.target
```

=========
```
[root@k8s-m1 ~]# cat  /etc/kubernetes/flanneld.kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxakNDQWI2Z0F3SUJBZ0lKQU1WOFUzYTEwdnhVTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmd4RmpBVUJnTlYKQkFNTURXdDFZbVZ5Ym1WMFpYTXRZMkV3SGhjTk1Ua3dOekV4TURZeE1ETXdXaGNOTkRZeE1USTJNRFl4TURNdwpXakFZTVJZd0ZBWURWUVFEREExcmRXSmxjbTVsZEdWekxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFzcDJ2Vm43UFVqcGZtemx2TFhHU0lmNmkxakhjb3BHcjZKRzREMi9XUWRoUnAxVHUKU3hwdXYyR0h3RHM4bEtPYk9hKzFMc1JSbGxybkdscloyOFdGSzM3dnowcEpXS3ByYjRqMWhZaVJCU3MrWjkrNwpRb3pCeFlmeTZKakp4NTdjNm9UWVpNakM3WWlBNnpGLzJ3YVZYMks5SDlmajNYMWFxNmMxdzJtVkFhK2xDVW5mCktrTUxNaUROdmZKa1Q0NlJCVk03QjRFb3Z2U0diOXJiNHd0V2o0MGxoSDRjbDJ2UmNMam9WQUx5a1BYZXduU0kKUW9sd0c4dXBMd3FTRzN4U3FVUS8xRGlBVmoyMFpHeEwzWUozQVUzMVRwdUt4Mm00SkdIeUpjUDBGWVhHRE1Mawo5WG5tZ011aEtVdE9haE9UWGJNVWNhcU1ZTU9pT3JrMDAxajNHd0lEQVFBQm95TXdJVEFQQmdOVkhSTUJBZjhFCkJUQURBUUgvTUE0R0ExVWREd0VCL3dRRUF3SUNwREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSTJvSjJJczUKUS9PdkZya2pvRitXTlJWbE93MkQyTjRYY3drZ3hXNVdMTXhSRHZSaTNqTHQzSkloMERkdHlSSExmKzdVSWJoVwpySHAxL3dUN1AvWmJsZ2RMVm9hS0s2SS9jUTF2NC9XRFNCdVVqWG1hRm4zTndGWDR1dVN1Z215ckIxMXk1blB4CnlVZmsva0tFVE5uSjlzV2syOWM1ZE1Wd2JJQnMxSzV4V0xYOVJYeEIvTjhIeHZxa1M5UkRMMUM2WUhERDhrQkYKV2o1ZGtHcDFtS1B3dXN2R2JWLy9nWnJRVUdHZHhsYjZqVE1BQjVKYkUzTGZCOHVBaUNNdTk1Z2VqWFhlZmhEMQpLSHNIeEUrZDVLRTdNNEtNekJLeHRwQ2F4c0dBQmFMVk5jZDZXRDdqY2UxZ01Ta2xEdDBqUklGcjVFbWJRUnFpCjVhZXZrYVlGeTk1dUNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.11.240:8443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes
  user: {}
```
=========

博主回复真快啊[爱心]

我不懂其中原理，所以看不懂，帮我看看
