### ISSUE TITLE
ansible-playbook deploy.yml --tags tls 出错

### ISSUE THREAD

**Issue by kevinzu007** [zhangguanzhang/Kubernetes-ansible#6]
ansible-playbook deploy.yml --tags tls 出错（我用的是独立ansible机器，不是master0），信息如下：

TASK [tls : apiserver-etcd-client --- part.1] *************************************************************************************************************************************************
changed: [localhost]

TASK [tls : apiserver-etcd-client --- part.2] *************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "openssl x509 -in apiserver-etcd-client.csr -req -CA etcd/ca.crt -CAkey etcd/ca.key -CAcreateserial -extensions v3_req_etcd -extfile openssl.cnf -out apiserver-etcd-client.crt -days 10000\n", "delta": "0:00:00.013557", "end": "2019-07-10 15:03:09.043126", "msg": "non-zero return code", "rc": 1, "start": "2019-07-10 15:03:09.029569", "stderr": "Error Loading extension section v3_req_etcd\n140280250644368:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:v3_alt.c:476:value=etcd001.k8s.local\n140280250644368:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=subjectAltName, value=@alt_names_etcd", "stderr_lines": ["Error Loading extension section v3_req_etcd", "140280250644368:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:v3_alt.c:476:value=etcd001.k8s.local", "140280250644368:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=subjectAltName, value=@alt_names_etcd"], "stdout": "", "stdout_lines": []}

**Comment by kevinzu007** [comment]
commit e1e0f50c6c978ad3750f50a4f8b743396eeadd6e
Merge: 0a83f6e 2a48ee3
Author: zhangguanzhang <zhangguanzhang@qq.com>
Date:   Sun May 19 18:42:38 2019 +0800
这个提交是可以成功的

----------------------------------
commit 122e5717a04aff5eb921cba50dbd8dc3d767870a
Author: zhangguanzhang <zhangguanzhang@qq.com>
Date:   Tue Jul 9 15:26:29 2019 +0800

    fix docker version choose

commit 339e6466bc97941655574b9e8115d7c3ab61df0a
Author: zhangguanzhang <zhangguanzhang@qq.com>
Date:   Wed Jun 19 14:51:44 2019 +0800

    update coredns to version 1.5.0
    
    update coredns to version 1.5.0

commit e1e0f50c6c978ad3750f50a4f8b743396eeadd6e
Merge: 0a83f6e 2a48ee3
Author: zhangguanzhang <zhangguanzhang@qq.com>
Date:   Sun May 19 18:42:38 2019 +0800

    Merge pull request #2 from system51/test
    
    add the user for the script at the keepalived of the high version

**Comment by zhangguanzhang** [comment]
看下/etc/kubernetes/pki/openssl.cnf文件内容

**Comment by zhangguanzhang** [comment]
最新的推送里已经修复，group_vars/all.yml内容变动部分为
```
# don't delete the domain list var
certSANs:
  apiServer:
    - apiserver.k8s.local
    - apiserver001.k8s.local
    - apiserver002.k8s.local
    - apiserver003.k8s.local
#    - 100.64.2.50
#    - 100.64.2.51
  etcd:
    - etcd001.k8s.local
    - etcd002.k8s.local
    - etcd003.k8s.local
#    - 100.64.2.50
```
然后更改了下`roles/tls/temapltes/openssl.cnf.j2`的渲染逻辑判断，对填入ip或者域名分离渲染index
